# DataSource配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_bank_app_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # spring boot jpa 透過以下設定,整合了原本 jpa 在 persistence.xml 的相關設定
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


#server setting
server:
  port: 10021