# DataSource配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_bank_app_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # spring boot jpa 透過以下設定,整合了原本 jpa 在 persistence.xml 的相關設定
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    #hibernate
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true


#server setting
server:
  port: 10021

#logging
logging:
  config: classpath:logback-spring.xml
  level:
    com.jay: INFO